global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "instagram-monitor"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Load rules
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django"
    static_configs:
      - targets:
          [
            "backend1:8000",
            "backend2:8000",
            "backend3:8000",
            "backend4:8000",
            "backend5:8000",
          ]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "elasticsearch"
    static_configs:
      - targets:
          ["elasticsearch1:9200", "elasticsearch2:9200", "elasticsearch3:9200"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:9101", "kafka2:9101", "kafka3:9101"]
